// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1YMeNuNtYLCSIANEL1JDbBXC3C98ewRA',
    appId: '1:608978522646:web:49ee98539b814b55b3db37',
    messagingSenderId: '608978522646',
    projectId: 'farmos-trade-seller',
    authDomain: 'farmos-trade-seller.firebaseapp.com',
    storageBucket: 'farmos-trade-seller.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAavkixSUfXfqSFjdEW5TrkQN5ft1DPXdw',
    appId: '1:608978522646:android:4f2ca9221165d0fcb3db37',
    messagingSenderId: '608978522646',
    projectId: 'farmos-trade-seller',
    storageBucket: 'farmos-trade-seller.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrSYX-wkf4q-52cVEDPZyqO6Nz6yYKI9M',
    appId: '1:608978522646:ios:b2bbf1d96c7096b4b3db37',
    messagingSenderId: '608978522646',
    projectId: 'farmos-trade-seller',
    storageBucket: 'farmos-trade-seller.appspot.com',
    iosBundleId: 'com.example.tradeSeller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrSYX-wkf4q-52cVEDPZyqO6Nz6yYKI9M',
    appId: '1:608978522646:ios:b2bbf1d96c7096b4b3db37',
    messagingSenderId: '608978522646',
    projectId: 'farmos-trade-seller',
    storageBucket: 'farmos-trade-seller.appspot.com',
    iosBundleId: 'com.example.tradeSeller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1YMeNuNtYLCSIANEL1JDbBXC3C98ewRA',
    appId: '1:608978522646:web:ea8f9dd265f52e90b3db37',
    messagingSenderId: '608978522646',
    projectId: 'farmos-trade-seller',
    authDomain: 'farmos-trade-seller.firebaseapp.com',
    storageBucket: 'farmos-trade-seller.appspot.com',
  );

}